### ISSUE TITLE
Disable when <4 threads are available 

### ISSUE THREAD

**Issue by Madis0** [wisecase2/StutterFix#1]
The Modrinth listing has this warning:

> Warning, this mod does not work well for processors with 4 threads and below.

So why does the mod just not disable itself on such devices?

**Comment by wisecase2** [comment]
I'm bad with words, the mod works despite not removing the stuttering, the stuttering is reduced for 4 thread processors (previous versions). For dual core and single core processors it makes no difference whether you have this mod or not. Recently I solved the problem for 4-thread processors by reducing the number of workers from 2 to 1.

**Comment by wisecase2** [comment]
Although it cannot make changes to the number of workers in dual core and single core, it does change the priority for client/render thread to maximum. I will do more tests with priorities and I need your feedback to fix the mod's problems.
