### ISSUE TITLE
 Conflict crash with "bedrockify-1.9.1+mc1.20.4"

### ISSUE THREAD

**Issue by Zorklis** [wisecase2/StutterFix#3]
So I'm getting a crash with stutterfix when bedrockify mod is around.
[crash-2024-01-08_05.03.12-client.txt](https://github.com/wisecase2/StutterFix/files/13855902/crash-2024-01-08_05.03.12-client.txt)
After testing out which of my other 186 used mods it was, it turns out Stutterfix does not like Bedrockify, without stutterfix, it works fine and stutterfix without bedrockify.

Used: "stutterfix-mc1.20.3-0.1.9"
Fabric 1.20.4 api 
"bedrockify-1.9.1+mc1.20.4"

**Comment by wisecase2** [comment]
I released version 0.2.0 fixing the problem, the problem was the button in the menu that was conflicting with my mod.
