### ISSUE TITLE
Add an option to disable StutterFix button

### ISSUE THREAD

**Issue by StunfMC** [wisecase2/StutterFix#4]

**Comment by BlueJayofEvil** [comment]
I second this for a compatibility reason: It causes overlap with Cosmetica's button if both are enabled.
Moving or disabling the button would fix this.

![2024-03-20_02 17 25](https://github.com/wisecase2/StutterFix/assets/1016034/d5f34fb1-3f07-420a-adbe-752c4eedfbd3)

**Comment by Fernan181** [comment]
Also, the button overlapped with buttons from other mods like in https://github.com/wisecase2/StutterFix/issues/4#issuecomment-2014260705

**Comment by Jszp03** [comment]
Yep, tons of issues for a usless config that has like 3 options

**Comment by wisecase2** [comment]
I added an option to disable the button in version 0.2.3.
