### ISSUE TITLE
Settings reset every time the mods folder is updated

### ISSUE THREAD

**Issue by Gamba04** [wisecase2/StutterFix#9]
I'm a bit new to Minecraft mods, so I may be overlooking a technical limitation here but I noticed the **StutterFix Options** menu resets it's values to default every time I add or delete any mod in the mods folder.

I feel like this mod really works best when you fine-tune it to your individual needs, so it's important to not lose this data over time.

Is there any way that this could be fixed? Maybe storing the settings in a `.txt` in some subfolder of `.minecraft`?

**Comment by wisecase2** [comment]
The settings are stored in the config folder named stutterfix-config.json, I tested it here and had no problem, are you sure you didn't delete the stutterfix-config.json file from the config folder inside .minecraft? What version of the mod are you using?

**Comment by Gamba04** [comment]
Got it! I think I see the problem now, it has nothing to do with the `mods` folder as I initially thought.

What's happening is that the `stutterfix-config.json` file is not being updated when you change the settings. They are being applied in game and seem to be stored in RAM after closing and reopening worlds. However, anytime I close and open back the program, they're back to the default settings.

I checked the file before closing Minecraft and it doesn't change it's values.

**Comment by Gamba04** [comment]
I fixed it for now by just setting the values manually in the config file, but maybe give it a look anytime you can and see if you can reproduce it.

I'm using the latest version **StutterFix mc1.21-0.2.0** btw, I forgot to mention.

**Comment by wisecase2** [comment]
I launched mc1.21-0.2.1 with the problem resolved, it seems that it was my mistake, Mojang changed the way the interface works a lot and when I changed the code I ended up forgetting it when closing the configuration.

**Comment by Gamba04** [comment]
Wow, I think you might be the fastest coder I've seen! Thank you so much!
